# Generated by Django 4.2.25 on 2025-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_user_email_6f2530_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='users_user_role_36d76d_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
